### ISSUE TITLE
Limit to current wp version

### ISSUE THREAD

**Issue by cfoellmann** [AlphawolfWMP/disable-wordpress-updates#3]
I am thinking about what is not needed for the current (4.9 at the moment) wp release.
Are the versions in the comments correct? Like
```
/*
		 * Disable Core Updates
		 * 2.8 to 3.0
		 */
```

I am not a noob but I don't want to do all the research. I trust you did/ and do this properly.

**Comment by AlphawolfWMP** [comment]
Hi cfoellmann, I wouldn't want to limit the plugin's possible audience by only supporting the current WP version, but you're right that I wouldn't need the code snippet that you were referencing anymore as the plugin requires ar least WP 3.4.

Thank you!

**Comment by cfoellmann** [comment]
I didn’t want to suggest you do that but I might.
So I only have to look for the 3.7+ stuff, right?

**Comment by AlphawolfWMP** [comment]
@cfoellmann Basically yes. I wouldn't rely on the "to" parts of the "* 2.8 to 3.0" comments though as they may be outdated, e.g. "* 3.8 to 4.5" may also be still used in WP 4.9 because I just missed to update the comments.
